[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
image = "0.21.1"
num-complex = "0.2.1"
